server:
  port: 9090
eureka:
  instance:
    hostname: eureka9090.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka9190.com.com:9190/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000